wasi-sdk\\bin\\clang ^
-Os ^
--sysroot wasi-sdk/share/wasi-sysroot ^
-nostartfiles ^
-Wl,--no-entry ^
-D_WASI_EMULATED_SIGNAL ^
-D_SIGNAL_H ^
-DDEFAULT_DPI=96 ^
-I. ^
-Igraphviz/lib ^
-Igraphviz/lib/gvc ^
-Igraphviz/lib/common ^
-Igraphviz/lib/pathplan ^
-Igraphviz/lib/cgraph ^
-Igraphviz/lib/cdt ^
graphviz/lib/cdt/dtclose.c ^
graphviz/lib/cdt/dtdisc.c ^
graphviz/lib/cdt/dtextract.c ^
graphviz/lib/cdt/dtflatten.c ^
graphviz/lib/cdt/dtlist.c ^
graphviz/lib/cdt/dtopen.c ^
graphviz/lib/cdt/dtrestore.c ^
graphviz/lib/cdt/dtsize.c ^
graphviz/lib/cdt/dtstrhash.c ^
graphviz/lib/cdt/dttree.c ^
graphviz/lib/cdt/dtview.c ^
graphviz/lib/cgraph/agxbuf.c ^
graphviz/lib/cgraph/apply.c ^
graphviz/lib/cgraph/attr.c ^
graphviz/lib/cgraph/agerror.c ^
graphviz/lib/cgraph/edge.c ^
graphviz/lib/cgraph/graph.c ^
graphviz/lib/cgraph/id.c ^
graphviz/lib/cgraph/imap.c ^
graphviz/lib/cgraph/io.c ^
graphviz/lib/cgraph/mem.c ^
graphviz/lib/cgraph/node.c ^
graphviz/lib/cgraph/obj.c ^
graphviz/lib/cgraph/pend.c ^
graphviz/lib/cgraph/rec.c ^
graphviz/lib/cgraph/refstr.c ^
graphviz/lib/cgraph/subg.c ^
graphviz/lib/cgraph/utils.c ^
graphviz/lib/cgraph/write.c ^
graphviz/lib/common/arrows.c ^
graphviz/lib/common/colxlate.c ^
graphviz/lib/common/ellipse.c ^
graphviz/lib/common/emit.c ^
graphviz/lib/common/geom.c ^
graphviz/lib/common/globals.c ^
graphviz/lib/common/htmllex.c ^
graphviz/lib/common/htmltable.c ^
graphviz/lib/common/input.c ^
graphviz/lib/common/intset.c ^
graphviz/lib/common/labels.c ^
graphviz/lib/common/memory.c ^
graphviz/lib/common/ns.c ^
graphviz/lib/common/output.c ^
graphviz/lib/common/pointset.c ^
graphviz/lib/common/postproc.c ^
graphviz/lib/common/psusershape.c ^
graphviz/lib/common/routespl.c ^
graphviz/lib/common/shapes.c ^
graphviz/lib/common/splines.c ^
graphviz/lib/common/taper.c ^
graphviz/lib/common/textspan.c ^
graphviz/lib/common/timing.c ^
graphviz/lib/common/utils.c ^
graphviz/lib/common/xml.c ^
graphviz/lib/dotgen/*.c ^
graphviz/lib/gvc/gvc.c ^
graphviz/lib/gvc/gvcontext.c ^
graphviz/lib/gvc/gvconfig.c ^
graphviz/lib/gvc/gvdevice.c ^
graphviz/lib/gvc/gvevent.c ^
graphviz/lib/gvc/gvjobs.c ^
graphviz/lib/gvc/gvlayout.c ^
graphviz/lib/gvc/gvloadimage.c ^
graphviz/lib/gvc/gvplugin.c ^
graphviz/lib/gvc/gvrender.c ^
graphviz/lib/gvc/gvtextlayout.c ^
graphviz/lib/gvc/gvusershape.c ^
graphviz/lib/label/index.c ^
graphviz/lib/label/node.c ^
graphviz/lib/label/rectangle.c ^
graphviz/lib/label/split.q.c ^
graphviz/lib/label/xlabels.c ^
graphviz/lib/pack/ccomps.c ^
graphviz/lib/pack/pack.c ^
graphviz/lib/pathplan/*.c ^
graphviz/lib/xdot/xdot.c ^
graphviz/plugin/core/gvrender_core_dot.c ^
graphviz/plugin/core/gvrender_core_svg.c ^
graphviz/plugin/dot_layout/gvlayout_dot_layout.c ^
graphviz/plugin/dot_layout/gvplugin_dot_layout.c ^
grammar.c ^
htmlparse.c ^
plugin.c ^
scan.c ^
undefined.c ^
dot2svg.c ^
-o dot2svg.wasm
