wasi-sdk\\bin\\clang ^
-Os ^
--sysroot wasi-sdk/share/wasi-sysroot ^
-nostartfiles ^
-Wl,--no-entry ^
-D_WASI_EMULATED_SIGNAL ^
-D_SIGNAL_H ^
-DDEFAULT_DPI=96 ^
-I. ^
-Igraphviz/lib ^
-Igraphviz/lib/gvc ^
-Igraphviz/lib/common ^
-Igraphviz/lib/pathplan ^
-Igraphviz/lib/cgraph ^
-Igraphviz/lib/cdt ^
graphviz/lib/cdt/dtclose.c ^
graphviz/lib/cdt/dtdisc.c ^
graphviz/lib/cdt/dtextract.c ^
graphviz/lib/cdt/dtflatten.c ^
graphviz/lib/cdt/dtopen.c ^
graphviz/lib/cdt/dtrestore.c ^
graphviz/lib/cdt/dtsize.c ^
graphviz/lib/cdt/dtstrhash.c ^
graphviz/lib/cdt/dttree.c ^
graphviz/lib/cdt/dtview.c ^
graphviz/lib/cgraph/agxbuf.c ^
graphviz/lib/cgraph/apply.c ^
graphviz/lib/cgraph/attr.c ^
graphviz/lib/cgraph/agerror.c ^
graphviz/lib/cgraph/edge.c ^
graphviz/lib/cgraph/graph.c ^
graphviz/lib/cgraph/id.c ^
graphviz/lib/cgraph/imap.c ^
graphviz/lib/cgraph/io.c ^
graphviz/lib/cgraph/mem.c ^
graphviz/lib/cgraph/node.c ^
graphviz/lib/cgraph/obj.c ^
graphviz/lib/cgraph/pend.c ^
graphviz/lib/cgraph/rec.c ^
graphviz/lib/cgraph/refstr.c ^
graphviz/lib/cgraph/subg.c ^
graphviz/lib/cgraph/utils.c ^
graphviz/lib/common/colxlate.c ^
graphviz/lib/common/emit.c ^
graphviz/lib/common/geom.c ^
graphviz/lib/common/labels.c ^
graphviz/lib/common/memory.c ^
graphviz/lib/common/utils.c ^
graphviz/lib/gvc/gvc.c ^
graphviz/lib/gvc/gvcontext.c ^
graphviz/lib/gvc/gvconfig.c ^
graphviz/lib/gvc/gvdevice.c ^
graphviz/lib/gvc/gvjobs.c ^
graphviz/lib/gvc/gvlayout.c ^
graphviz/lib/gvc/gvplugin.c ^
graphviz/lib/gvc/gvrender.c ^
grammar.c ^
scan.c ^
undefined.c ^
dot2svg.c ^
-o dot2svg.wasm
